### ISSUE TITLE
Preview fails with error (unable to open \Preview)

### ISSUE THREAD

**Issue by NenoLoje** [joaompinto/asciidoctor-vscode#1]
In VS Code on Windows, when trying to turn on the preview with:

- Open Preview to the Side
- or: Toggle Preview

it shows the error:

> Unable to open '\Preview: 'README.asciidoc'': Error 

Any ideas what could be going wrong, or how to troubleshoot this?

![error-aciidoc-vscode](https://cloud.githubusercontent.com/assets/13981145/19925880/3498c2cc-a0f2-11e6-8f5b-c1a59220246f.png)

Thanks,
--Neno

**Comment by joaompinto** [comment]
Hi, please try: View -> Debug Console, and then press the CTR-K r, hopefully it will report the error on the debug console.

**Comment by NenoLoje** [comment]
Thanks for the suggestion. I tried, but unfortunately the *Debug Console* remains empty. :(

**Comment by joaompinto** [comment]
Right, so let's do some requirements check, this extension requires "asciidoctor", are you using Windows or Linux ? Does "asciidoctor" on a terminal/command prompt work ?

**Comment by NenoLoje** [comment]
I'm running on WIndows.
Asciidoctor is installed, but possibly it's not defined in the PATH.

How are you detecting asciidoctor?

**Comment by NenoLoje** [comment]
I think this is it. When adding the ruby/asciidoctor folder to %PATH%, it works as expected.

Maybe you could:
(1) Handle the detection error more gracefully, in cases where asciidoctor is not installed or %PATH% not set correctly.
(2) Optionally, be more flexible and allow users to set the path and not rely on %PATH%.

**Comment by joaompinto** [comment]
Neno,
you can setup the path in the extension config.
File -> Preferences -> User Setttings,
you need to copy the required setting into your local config:
"AsciiDoc.html_generator": "YOUR_PATH\asciidoctor -o-" .

Anyway I will let this issue open, will close it with after adding the code for your suggestion (2), it should report that asciidoctor is missing from the path.

**Comment by NenoLoje** [comment]
Sounds good - thanks a lot, João!

**Comment by NenoLoje** [comment]
PS: Just to let you know. It's working great now. Thanks for the good work, João!

**Comment by joaompinto** [comment]
PS: Thanks for reporting. The error message with a suggestion for the path config was added on the new version.

**Comment by arulrajnet** [comment]
I am getting the same error in ubuntu 16.04. 
![image](https://user-images.githubusercontent.com/834529/28244660-e06c38d8-6a0d-11e7-84ca-73cf5a6b5e4b.png)

Asciidoctor 1.5.4

PATH of asciidoctor bin `/usr/bin/asciidoctor`

`asciidoctor -o- 1-introduction.asc` prints html on terminal.

![image](https://user-images.githubusercontent.com/834529/28244673-4e50b360-6a0e-11e7-84f5-603255cf6531.png)

there is no error in vscode Debug console.

**Comment by arulrajnet** [comment]
Found the problem. I am using another extension for [reStructuredText](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext). That causing the problem. After disable that its working fine. Thanks for this nice extension

![image](https://user-images.githubusercontent.com/834529/28244868-e19b0408-6a14-11e7-8049-ce1a39a53be3.png)

**Comment by rathiram1978** [comment]
I had Restructured Text previewer installed. Disabling the plugin solved the issue. Thanks !
