### ISSUE TITLE
Extension doesn't work at all

### ISSUE THREAD

**Issue by RichardJECooke** [joaompinto/asciidoctor-vscode#106]
I installed the extension:
![untitled](https://user-images.githubusercontent.com/5468805/44956902-2a88c280-aecb-11e8-818d-598096983925.png)

And made a new .adoc file with the content from a cheatsheet example here: https://raw.githubusercontent.com/asciidoctor/asciidoctor.org/master/docs/asciidoc-syntax-quick-reference.adoc

But when clicking the preview button (or ctrl-shift-v) nothing happens:
![untitled](https://user-images.githubusercontent.com/5468805/44956919-63289c00-aecb-11e8-953a-9e5c0aa90dd8.png)

What to do please?

**Comment by joaompinto** [comment]
Try CTRL-K followed by V. or F1, then type: AsciiDoc... Please provide the error if it shoes some error in the status bar.

**Comment by RichardJECooke** [comment]
Thank you!  Using the F1 method works. Weird, even though I can see clearly in my keyboard shortcuts now that ctrl-K V is there, it just do anything, even though it works fine for markdown files.

![untitled](https://user-images.githubusercontent.com/5468805/44957188-8c4b2b80-aecf-11e8-89bb-d5cc1b71a1e3.png)
