### ISSUE TITLE
Add support for location synchronization between editor and preview

### ISSUE THREAD

**Issue by itsdani** [joaompinto/asciidoctor-vscode#11]
It would be great if the preview jumped to the modified location if it is out of view. Similarly it would be really nice if the editor could be scrolled to a certain position by e.g. double clicking in the preview. Similar features are implemented in the `Brackets` editor for asciidoc, but I haven't seen it in any other editor/preview plugin.

**Comment by joaompinto** [comment]
I am looking into this, the VSCode built-in extension for markdown files already does  "scroll sync", but the code is somehow complex. I  will do some more research on that code.

**Comment by diiigle** [comment]
+1

**Comment by zoeminghong** [comment]
wish

**Comment by danyill** [comment]
I am super keen for better syncing as well. My coding skills are quite modest but hopefully I can be a research assistant!

See https://github.com/asciidoctor/asciidoctor.js/issues/127

1. I think we need to run Asciidoctor with `sourcemap=true`
2. We then call `find_by` which returns all nodes
3. We then iterate across these and call [`source_location().line_no`](https://github.com/asciidocfx/AsciidocFX/blob/d76e6d2116205746b235539c6193550e197b8361/conf/public/js/prototypes.js#L7) or similar. We then manipulate the object model to add this information.
4. @rahmanusta [has implemented a TreeProcessor](https://github.com/asciidocfx/AsciidocFX/blob/4b5bd06f8f54f003b8644ee6b26d8186d55105fe/conf/public/js/asciidoctor-data-line.js) (thanks!)  which may be very similar to what is needed here in [AsciidocFX](https://github.com/asciidocfx/AsciidocFX) which adds the line number to the role.

**Comment by joaompinto** [comment]
Metadata is in https://github.com/joaompinto/asciidoctor-vscode/commit/9f04dad0852532f0b52ce42346f58076d3af61dc

I had to look at the AsciidoctorJS source to figure how to use loadFile(), findBy(), getLineNumber(). addRole() .

I need to contribute to improve the documentation from https://github.com/asciidoctor/asciidoctor.js/blob/master/docs/manual.adoc , once this issue gets closed. I am missing the mapping/scroll part in VS Code :)

**Comment by joaompinto** [comment]
I have been looking into markdowns's synchronization code, and from my understanding, it depends in a feature (vscode.window.createWebview) which is only available from the "proposed API", which is restricted to internal VSCode extensions. 

Will be tracking https://github.com/Microsoft/vscode/issues/28263, hoping that createWebview becomes available for general use.

**Comment by joaompinto** [comment]
After some research I was able to figure a solution for the preview sync with source. Is not perfect but I was the best I could do :P . Those who have the skills please checkout from git, test it, and provide some feedback. 

The preview is now "omnidoc", meaning you  just need one view for multiple docs,t will get updated depending on the .adoc that is being edited.

The preview is "moved":
- When text is changed
- When text is selected

**Comment by joaompinto** [comment]
I am confident on the new code, applied to the newer release.

**Comment by danyill** [comment]
@joaompinto 

I've had a play and it looks good to me. Thanks!

I am interested in making the preview work correctly with Asciidoctor includes at some stage and will raise an issue for this. I'm playing around with some ways to do this.
