### ISSUE TITLE
Possible regression: image preview no longer working as before

### ISSUE THREAD

**Issue by mgroves** [joaompinto/asciidoctor-vscode#12]
I just installed the latest AsciiDoc in Code (0.3.1), and now the images links are broken in preview.

In my file:

`:imagesdir: images` is at the top

`image:059_01_Couchbase_Web_Console.png[Couchbase Web Console login]` is later in the post

And in the preview:

![2017-03-17 10_11_21-blogpost adoc - groves - visual studio code](https://cloud.githubusercontent.com/assets/103484/24046770/186005c6-0afa-11e7-91c6-67eb70f66c56.png)

Am I doing something wrong, or is this a regression?

**Comment by joaompinto** [comment]
Fix published to the marketplace on 0.3.2 .
