### ISSUE TITLE
Cannot move preview tab to a separate window

### ISSUE THREAD

**Issue by slavashvets** [joaompinto/asciidoctor-vscode#14]
#### VSC
Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:02:52.799Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

#### OS
Windows 7 x64

#### Steps to Reproduce

1. Open two separate windows
2. Open asciidoctor document with a preview tab
3. Drag the a preview tab from one window to the tab bar in the other window
4. Nothing happens? I would expect this to move the tab to the window I just dragged it to

**Comment by joaompinto** [comment]
Thanks for reporting the issue, since this is a vscode general issue (it affects any kind of preview tab, including core tabs), I have opened the issue for vscode https://github.com/Microsoft/vscode/issues/24359 . 
Closing this one.
