### ISSUE TITLE
Broken on VSCode 1.11.0

### ISSUE THREAD

**Issue by marekr** [joaompinto/asciidoctor-vscode#15]
Attempting to open a preview window on 1.11.0 causes a error.

"Cannot read property 'document' of undefined."

This is probably due to the new workspaces feature. Really sucks how VSCode can't maintain API compatibility worth a damn due to JS land.

**Comment by joaompinto** [comment]
Hello,
it's working for me on 1.11, are you using Linux or Windows ?

**Comment by marekr** [comment]
Windows.

I just updated on a second PC witht he same result.

**Comment by fabianlaule** [comment]
Same here with 1.11.2 and OS X

**Comment by sanguine8082** [comment]
works ok for me.  

Windows 7 1.11.2

**Comment by brettenbacher** [comment]
Same happens with my installations:
Tried out 1.11.2 and 1.12.0 (insider) on Ubuntu 16.04 and 1.11.2 on OS X (all fresh installs) using Asciidoctor 1.5.5.

**Comment by FrVaBe** [comment]
Preview also fails for me on(Windows 7 with message "Cannot read property 'document' of undefined." 

- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|markdown-toc|AlanWalk|1.5.1|
|asciidoctor-vscode|joaompinto|0.3.3|;

**Comment by elfgoh** [comment]
I confirm this issue on Mac OS, version ` 1.12.2`

**Comment by joaompinto** [comment]
Fixed on 0.3.5 .

**Comment by sanguine8082** [comment]
Scratch that, Open Preview to side works, but Open Preview does not

**Comment by marekr** [comment]
@sanguine8082 have you upgraded to 0.3.5 (you have to manually click upgrade)? It should work in all cases now after I fixed it.

**Comment by sanguine8082** [comment]
Oh, my mistake!  

Definitely works now.  Thanks a bunch!
