### ISSUE TITLE
"Operation not permitted" using previewToSide when not Administrator (Windows)

### ISSUE THREAD

**Issue by Bill-Stewart** [joaompinto/asciidoctor-vscode#18]
Windows 7
VS Code: 1.11.2
AsciiDoctor: 0.3.3

Reproduce:

1. Start VS Code as non-administrator

2. Change empty file type to AsciiDoc

3. Use command `adoc.previewToSide`

This gives an error like the following:

`Unable to open '\Preview: 'Untitled-1'': EPERM: operation not permitted, open 'C:\Program Files (x86)\Microsoft VS Code\tmp-6068uPBApv0Y5nNQ.adoc'.`

**Comment by tats-u** [comment]
I'm bothered with this issue, too.  I wonder why it is left for a long time.  My environment is:

- Windows 10
- Visual Studio Code 1.18.
- AsciiDoctor 1.5.6.1

**Comment by joaompinto** [comment]
This should be fixed now, please reopen the issue if you are still getting the error.
