### ISSUE TITLE
Asciidoctor-vscode 0.3.3 won't install OS X 10.12.5 VSC 1.12.2

### ISSUE THREAD

**Issue by tonykay** [joaompinto/asciidoctor-vscode#19]
Both via the GUI and the cmd-line it won't install. cmd-line more helpful. Following these steps:

git clone https://github.com/joaompinto/asciidoctor-vscode
cd asciidoctor-vscode
npm install
sudo npm install -g vsce
vsce package
code --install-extension *.vsix

I get:

[ { Error: ENOENT: no such file or directory, open '/Users/tok/.vscode/extensions/joaompinto.asciidoctor-vscode-0.3.3/package.json'
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/Users/tok/.vscode/extensions/joaompinto.asciidoctor-vscode-0.3.3/package.json' } ]

Now if I copy the package.json file in manually, I still get the same issue. I assume because code --install-extension *.vsix removes Users/tok/.vscode/extensions/joaompinto.asciidoctor-vscode-0.3.3 and starts over from scratch.

Vexing. FWIW this problem didn't manifest itself until I installed various other bits of the the whole asciidoc world (ascidoctor, plus some alignedstuff such as dblatex)

**Comment by joaompinto** [comment]
Could you please test with 0.3.4 which was published today ? Thanks

**Comment by tonykay** [comment]
Sorry for the delay... Latest version 0.3.7 works with Code 1.18.
I'm going to clone the repo and in the unlikely event I have time will try to work on the code syntax highlighting e.g.

----
my code here
----
Then I can move from Atom to VS Code ;)
