### ISSUE TITLE
Bad color after a monospaced string that start with #

### ISSUE THREAD

**Issue by bdesemb** [joaompinto/asciidoctor-vscode#22]
Here is an example in image.

![screen shot 2017-07-13 at 14 48 58](https://user-images.githubusercontent.com/3394197/28167136-ceec727e-67da-11e7-848f-bb220bda0ae2.png)

The remaining parts of the document is in this bad color also.

**Comment by joaompinto** [comment]
I don't have much experience with the syntax coloring engine (TextMate bundle), this addon is using one of the public available version. I will probably take some time to fix this. Thanks for reporting the problem.

**Comment by sanguine8082** [comment]
A workaround is to enclose the singular # with dollar signs (eg `$$#$$non lacinia...`), this is a directive to Asciidoctor to ignore the macro.  

Almost every theme I've encountered has issues with unpaired #, *, [, ], etc.

**Comment by Gigacee** [comment]
この問題を修正してみました。

syntaxes/Asciidoctor.tmLanguage を、以下に置き換えて下さい。

https://github.com/Gigacee/sublimetext-giga-asciidoc/blob/develop/Syntaxes/Asciidoctor.tmLanguage

※まだ十分なテストをしていないので、別のバグがあるかもしれません。

----

I tryed to fix it.

Replace syntaxes/Asciidoctor.tmLanguage to below:

https://github.com/Gigacee/sublimetext-giga-asciidoc/blob/develop/Syntaxes/Asciidoctor.tmLanguage

CAUTION: I have not done enough test yet, so there may be other bugs.
