### ISSUE TITLE
docker configuration

### ISSUE THREAD

**Issue by Arnotjevleesch** [joaompinto/asciidoctor-vscode#23]
Hi
I run asciidoctor thru docker like this : https://github.com/asciidoctor/docker-asciidoctor
I wonder how configure AsciiDoc.html_generator in vscode to use the docker run instead the default  asciidoctor -o-

Did you ever experiment this ?

**Comment by joaompinto** [comment]
You  no longer need asciidoctor to use the extenstion,  Please open the issue if needed. Thanks
