### ISSUE TITLE
can converted results show in browser such as chrome?

### ISSUE THREAD

**Issue by shlwang** [joaompinto/asciidoctor-vscode#24]
it is a useful feature since browser experiance is better

**Comment by sanguine8082** [comment]
I feel like that is out of scope for this plugin.  The idea is to show a side by side preview in the editor.  

If you want a preview in the browser, download the Asciidoctor.js Preview extension for Chrome.  That should work for you :smile:

**Comment by joaompinto** [comment]
I agree with @sanguine8082 , for browser experience you will be better server with a browser based plug-in, there are add-ons for asciidoc preview for most browsers..
