### ISSUE TITLE
asciidoctor is run too often

### ISSUE THREAD

**Issue by maverickwoo** [joaompinto/asciidoctor-vscode#25]
It's great to see some asciidoctor support in VSCode!

I am using VSCode 1.15.1 with v0.3.5 of this plugin on OSX. It seems that asciidoctor is run on every keystroke on a temp file, and this behavior can easily overwhelm even a powerful computer when the cursor is on a rapid movement because every keystroke launches a new instance of asciidoctor.

Aside from not running asciidoctor on non-editing keys (i.e., not on cursor movements) and not running multiple instances of asciidoctor simultaneously, I wish to see options like:

- run on save only
- run on temp file like it is today, but no more frequently than say (a default of) 5 seconds

Thank you!

**Comment by joaompinto** [comment]
This is fixed in the latest version, the extension only updates on save/update-timer, the check for updates timer can be changed in the settings, AsciiDoc.runInterval .

**Comment by hong-chan** [comment]
Seems AsciiDoc.runInterval is not working anymore in v2.3.3. 
Please advise.
