### ISSUE TITLE
Please don't use Ctrl-K for previewing

### ISSUE THREAD

**Issue by tadayosi** [joaompinto/asciidoctor-vscode#27]
`Ctrl-K` is by default bound to deleting all right on VSCode on Mac (and maybe other platforms). This extension is great but please don't hide the default `Ctrl-K` with the previewing shortcut.

**Comment by AndyGee** [comment]
+1 Yes, really bad key combi - Also ctrl+kr opens the keymap and not the preview.

**Comment by gdamore** [comment]
Because of this bug, I cannot use this extension!  Ctrl-K is a standard binding on all UNIX platforms (including Linux and MacOS) in shells, editors (emacs and vsc of course!) and means delete-to-EOL.

Overriding that (and not giving me any way to *turn that override off* means that your extension (which is otherwise quite interesting) is more trouble to me than its worth.  (This keybinding is wired into my brain.)

**Comment by gdamore** [comment]
This is not an "enhancement" request, it's a bug!  in fact, this keybinding stomps on all other modes, so that ctrl-k doesn't work when editing program source code (.c files), not just asciidoc files!

**Comment by gdamore** [comment]
Actually, the rebinding of Ctrl+Shift+R overrides another action (refactor) as well.  I don't use that, so it isn't as onerous to me, but it strikes me that overriding keybindings unconditionally is a *bad* idea in any event, and really should not be done at all unless its easily undone.

**Comment by gdamore** [comment]
Reading the guidance for VSC extension developers, it may be simple enough to just change the Ctrl-K to add a mac binding of CMD-K R, etc.  I'll prepare a PR to this effect.

**Comment by gdamore** [comment]
From what I can see, even cmd+k r is used, but cmd+k shift+cmd+r is not.  I'll set up that mapping.

**Comment by gdamore** [comment]
actually cmd+k shift+r is easier.

**Comment by joaompinto** [comment]
"ctrl+k shift+r" does not work on Linux (at least with gnome3), I am changing to "ctrk+k r, hope it works on windows.

**Comment by gdamore** [comment]
ctrl-k is still evil on Linux, and in retrospect, maybe we shouldn't have used that at all.  I'm not sure what the Linux port does -- I guess it doesn't use the "mac" bindings.

On all UNIX platforms, ctrl-k should clear-to-end-of-line, by itself.

**Comment by joaompinto** [comment]
On Linux VSCode just uses ctrl-k as a sequence holder, it just shows "Waiting for second key of chord.." and waits for the next key. Legacy UNIX keybindings have no meaning in modern editors :P
