### ISSUE TITLE
Use asciidoctor.js

### ISSUE THREAD

**Issue by gquintana** [joaompinto/asciidoctor-vscode#29]
To avoid installing the [asciidoctor Ruby edition](https://github.com/asciidoctor/asciidoctor), the [asciidoctor JavaScript edition](https://github.com/asciidoctor/asciidoctor.js) can be used.
Atom's AsciiDoc Preview plugin uses this library.

It could also be used as fallback solution, when asciidoctor Ruby is not found.

**Comment by sindzicat** [comment]
It will be beter, if user can choose engine to use. I use Ruby version of Asciidoctor. It's not difficult for me to make changes in Asciidoctor on Ruby, but I will have problems when I will need to modify js version of Asciidoctor.

**Comment by joaompinto** [comment]
@sindzicat I will add an option to enable/disable the asciidoctor js.
