### ISSUE TITLE
Add "GoTo" symbol in file, targetting headers

### ISSUE THREAD

**Issue by joaompinto** [joaompinto/asciidoctor-vscode#3]
We should be able to get into headers, as provided by the following extension for markdown:
https://marketplace.visualstudio.com/items?itemName=jrieken.md-navigate

**Comment by sanmai-NL** [comment]
You mean headings? You've implemented those already. 🙂  For those who end up here: <kbd>Ctrl-Shift-o</kbd>. Issue can be closed then?
