### ISSUE TITLE
Buffer size

### ISSUE THREAD

**Issue by danyill** [joaompinto/asciidoctor-vscode#33]
I very often get this on large Asciidoc files, particularly when I embedding in graphics.

```
Error

stdout maxBuffer exceeded Error: stdout maxBuffer exceeded at Socket.onChildStdout (child_process.js:270:14) at emitOne (events.js:96:13) at Socket.emit (events.js:191:7) at readableAddChunk (_stream_readable.js:178:18) at Socket.Readable.push (_stream_readable.js:136:10) at Pipe.onread (net.js:560:20) 

If the asciidoctor binary is not in your PATH, you can set the full path.
Go to `File -> Preferences -> User settings` and adjust the AsciiDoc.html_generator config option.

I fairly frequently get this error.
```

Suggest the stdout maxBuffer parameter be added to the configuration to give some flexibility here. I'll do a PR for this.

**Comment by joaompinto** [comment]
@danyill , in the last commit the exec() was replaced with spawn() which should not suffer from the buffering issue, could you please test it ? (if possible with use_asciidoctor_js set to true/false).

**Comment by joaompinto** [comment]
@danyill , in the last commit the exec() was replaced with spawn() which should not suffer from the buffering issue, could you please test it ? (if possible with use_asciidoctor_js set to true/false).

**Comment by joaompinto** [comment]
@danyill , in the last commit the exec() was replaced with spawn() which should not suffer from the buffering issue, could you please test it ? (if possible with use_asciidoctor_js set to true/false).

**Comment by joaompinto** [comment]
Thanks for the test, AsciiDoc.buffer_size_kB is no longer used. I can't reproduce the "AsciiDoc.use_asciidoctor_js": false issue, can you provide me some sample adoc ? In case it's system specific, you can run the extension on debug mode, the "Go to `File -> Preferences -> User settings`"  mesage should have an error reported on the debug console.
