### ISSUE TITLE
Preview for inter document cross reference

### ISSUE THREAD

**Issue by redtankd** [joaompinto/asciidoctor-vscode#35]
From Asciidoctor's User Manual

```
= Document Title
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

See the <<README#,README>>.

We could also write the link as link:README{outfilesuffix}[README].

The links in the generated document will now point to README.adoc instead of the default, README.html.
```

It is supported in `asciidoctor-vscode`?

**Comment by joaompinto** [comment]
asciidoctor-vscode uses  asciidoctor for the rendering, so yes, it supports everything that you get with the plain ascidoctor .

**Comment by redtankd** [comment]
Two more question. 

How to use `ifdef` in vscode? `env-github,env-browser` is not supported.

Are anchors supported in inter-document cross reference? It seems not to work.
