### ISSUE TITLE
Alt + click to follow link broken

### ISSUE THREAD

**Issue by sanmai-NL** [joaompinto/asciidoctor-vscode#36]
`https://github.com/[First word]` leads to `https://github.com/[First` as link. Can VSCode be instructed to make the link parsing syntax dependent?

**Comment by joaompinto** [comment]
I don't now much about the syntax highlight format, but I assume there is no support for flagging "urls". If there was such support, it would need to be integrated  VSCode's editor.links settings.

https://github.com/[First word] also breaks the url using the built-in markdown syntax, despite being correctly set in the markdown preview. If you believe that this feature is important, the bug should be open for VSCode itself :)
