### ISSUE TITLE
Mathjax doesn't work

### ISSUE THREAD

**Issue by AndreWin** [joaompinto/asciidoctor-vscode#37]
Hello!

VS studio version 1.19.0 Insider.

I tried to type any formula, for example, `stem::[\sin(x)]`, but see only `\$\sin(x)\$`. It seems for me, that mathjax isn't running for me.

How can I fix this? I restarted my vs code, but this didn't help me. Internet works fine.

Best regards,
Andrey.

**Comment by AndreWin** [comment]
I have [Asciidoctor.js Live Preview](https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia) in my Chrome. Formulas works fine in Chrome with this extension.

**Comment by AndreWin** [comment]
Can anybody help me?

**Comment by joaompinto** [comment]
Try using the latexmath macro:

latexmath:[C = \alpha + \beta Y^{\gamma} + \epsilon]

**Comment by AndreWin** [comment]
@joaompinto, oh, sorry, I was so stupid!
I forgot about `:stem: latexmath` after document title.
Now all works fine. Thank you very much!
