### ISSUE TITLE
Errors with stdout maxbuffer

### ISSUE THREAD

**Issue by sindzicat** [joaompinto/asciidoctor-vscode#39]
Hello!

I have .adoc file with 1000+ lines. I added new attribute to this document `:data-uri:`. After that I got the following error:
```
stdout maxBuffer exceeded Error: stdout maxBuffer exceeded at Socket.onChildStdout
 (child_process.js:270:14) at emitOne (events.js:96:13) at Socket.emit (events.js:191:7) at 
readableAddChunk (_stream_readable.js:178:18) at Socket.Readable.push (_stream_readable.js:136:10)
 at Pipe.onread (net.js:560:20)
```

Now I just use `asciidoctor -a data-uri mydoc.adoc` unstead.

How can I make this buffer bigger?

Best regards,
Andrey.

**Comment by joaompinto** [comment]
You need to increase the parameter   AsciiDoc.buffer_size_kB which is available from settings.

**Comment by sindzicat** [comment]
Thank you, @joaompinto.
