### ISSUE TITLE
Syntax highlighting breaks with # in source code mode (line indented)

### ISSUE THREAD

**Issue by ffasbend** [joaompinto/asciidoctor-vscode#42]
Exemple:
Install RVM along with the latest version of Ruby:

    $ curl -#L https://get.rvm.io | bash -s stable --autolibs=3 --ruby 

RVM will download and build the Ruby language.

Asciidoctor ignores a # in source code mode (indenting lines), however the syntax highlighter expexts a closing #, but doesn't find it.

**Comment by jokerr** [comment]
While not directly related to an indentation the highlighter seems to have a similar issue with URLs.  I've noticed that the issue seems to happen if the `#` (and `_`) are the first character after a slash.

Example:
Works as expected
```
* https://example.com/foo#bar
* https://example.com/foo_bar
```
Highlighting is broken
```
* https://example.com/#foobar
* https://example.com/_foobar
```

**Comment by joaompinto** [comment]
Could you please check with the latest extension version ? (I was unable to reproduce)

**Comment by ffasbend** [comment]
Thanks, seems OK now
