### ISSUE TITLE
can not open preview to the Side

### ISSUE THREAD

**Issue by stayfool** [joaompinto/asciidoctor-vscode#5]
error messge:
can not open “\Preview: 'test.adoc'”: Cannot read property 'document' of undefined。

windows, vscode version 1.8, portable version

**Comment by zgudino** [comment]
Hi,

Make sure you installed [AsciiDoctor](http://asciidoctor.org/#installation).

**Comment by stayfool** [comment]
@zgudino  I have installed AsciiDoctor,  It's OK now after I change my vscode to install version, it's maybe the vscode portable version's problem.

Now, there is a new problem, Admonitions in preview did show as picture.

**Comment by joaompinto** [comment]
You will need to setup your document with the css and icon attributes to support images, check http://asciidoctor.org/docs/user-manual/#icons .

**Comment by joaompinto** [comment]
Closing this issue for the original problem. Please open a new one if you still need help for the image based admotions.
