### ISSUE TITLE
Asciidoctor.js does not allow includes

### ISSUE THREAD

**Issue by danyill** [joaompinto/asciidoctor-vscode#50]
With the new default of using Asciidoctor.js, includes don't function correctly:

Without:

    "AsciiDoc.use_asciidoctor_js": false,

The following occurs for an include outside the current directory:

```
Unresolved directive in <stdin> - include
:../assets/attributes-include.adoc[]
```

There is some discussion of this error in node environments here:

https://github.com/asciidoctor/asciidoctor.js/issues/42

It does not seem to mattere if I use unsafe mode with the following in my settings:

```
"AsciiDoc.html_generator": "asciidoctor  --safe-mode=unsafe -o-",
```

Or whether the file is in the same directory or above it.
I wonder/suspect these options may not be passed to asciidoctor.js?

**Comment by danyill** [comment]
The problem seems to be caused by relative paths. It does appear to function correctly with Asciidoctor.js and an absolute path.

**Comment by joaompinto** [comment]
Thanks for the feedback. The fix is now available from the marketplace version.

**Comment by danyill** [comment]
Thank you. I confirm this works beautifully.

Thank you also for the Asciidoctor.js work -- this is a great development for this vscode extension and was on my to-do list (since there was a fork of your project which already did it and my users need single click installations). I think this will really help users of Asciidoctor without the Ruby dependencies.
