### ISSUE TITLE
Add an export as PDF option

### ISSUE THREAD

**Issue by joaompinto** [joaompinto/asciidoctor-vscode#58]
In order to publish/distribute documents most people rely on PDFs. An option to export to PDF should be implemented.

Possible solutions:
https://stackoverflow.com/questions/18191893/generate-pdf-from-html-in-div-using-javascript

**Comment by joaompinto** [comment]
After some research:
jsPDF - Does not work from nodejs (requires a window), could be implemented as the html view level, but it seems to have a rather limit html support
phantomjs - Requires a binary and requires a setup script
wkhtmltopdf - Requires a binary

At this time I am going to try with wkhtmltopdf because I have used in the past with successful results.

The hardest/ugliest part is that the extension will need to install platform specific binaries.

**Comment by danyill** [comment]
I see there is a wrapper for wkhtmltopdf (https://github.com/devongovett/node-wkhtmltopdf).

I'd suggest that just like Ruby for Asciidoctor, installation is the user's responsibility and if it is installed it is a valid option for the extension to use.

**Comment by joaompinto** [comment]
I am trying to implement an out-of-the-box experience, specially for less skilled windows users :)
In the first use the extension should offer the option to the dowload the binaries, but I can't figure how to use the relevant API functions:
https://stackoverflow.com/questions/49597116/how-do-we-use-the-latest-api-features
