### ISSUE TITLE
command 'adoc.previewToSide' not found

### ISSUE THREAD

**Issue by blueray453** [joaompinto/asciidoctor-vscode#62]
When I click `Open Preview to the Side [Ctd+K V]` it says 

`command 'adoc.previewToSide' not found`

However, when I use the shortcut key `Ctd+K V` it works.

**Comment by joaompinto** [comment]
I am a bit lost, about the "Open Preview To Side" ? Do you mean invoking it from the command dropbox ?

**Comment by blueray453** [comment]
It was giving `error command 'adoc.previewToSide' not found` when clicked on the marked section of the image.
![first](https://user-images.githubusercontent.com/855297/38470301-7c682b84-3b82-11e8-8f6e-084dc3e27ab8.png)
However, I just now tried to recreate the problem, so that I can give you a screenshot of the error, but it is just working fine.

**Comment by joaompinto** [comment]
Please reopen if you can reproduce it :)

**Comment by blueray453** [comment]
It is giving error `command 'adoc.previewToSide' not found` when clicked on the marked section of the image.
![first](https://user-images.githubusercontent.com/855297/38470301-7c682b84-3b82-11e8-8f6e-084dc3e27ab8.png)

The screenshot of error is given bellow 
![second](https://user-images.githubusercontent.com/855297/38483339-6c8eb13e-3bf4-11e8-8417-d0989dcf7e4f.png)

NOTE: However, when I use the shortcut key `Ctd+K V` it works.
