### ISSUE TITLE
wordwrap if the file type is .adoc

### ISSUE THREAD

**Issue by blueray453** [joaompinto/asciidoctor-vscode#65]
There is another important feature in markdown. If the file type is .md then it applies wordwrap automatically. 

```
// Configure editor settings to be overridden for [markdown] language.
  "[markdown]": {
    "editor.wordWrap": "on",
    "editor.quickSuggestions": false
  }
```
This seems to be a very important feature for some users.

Normally when we are writing article or books, we try not to press enter after the end of every line. We just want wordwrap when we are viewing it.
But we also write code in VSCode, then we do not want wordwrap enabled. 
So, if we have the liberty to configure to automatically turn on wordwrap if the doctype is .adoc then it will be great.

**Comment by joaompinto** [comment]
Thanks for the suggestion.
