### ISSUE TITLE
runInterval not beeing respected during document changes

### ISSUE THREAD

**Issue by crra** [joaompinto/asciidoctor-vscode#68]
Hello,

as mentioned in #67, I use the ruby interpreter with the digram extension to generate my documents. I know this is a very expensive process due to the external calls. However, I observe that for every keystroke (even with `refresh_interval` set to e.g. 5000ms) a new process is spawned. I would hope for some kind of throttling by managing the queue of re-renders.

_[update]_: I can confirm that this is not happening with the 0.5.0 version, but with the latest 0.7.1

**Comment by joaompinto** [comment]
Will be fixed in 0.7.2, but please be aware that the setting was also changed to "runInterval" (broken on 0.7.1).

**Comment by joaompinto** [comment]
0.7.2 was published, thanks for reporting the issue, it was really severe for large documents.

**Comment by crra** [comment]
@joaompinto LOL, I copied the variable name from the code and not from my config. The bug was right before my 👀.

**Comment by crra** [comment]
@joaompinto ok, looks good even with `runInterval = default`

Thanks for the quick fix.
