### ISSUE TITLE
Coderay css error

### ISSUE THREAD

**Issue by SandMann1** [joaompinto/asciidoctor-vscode#69]
My asciidocs use coderay as source code highlighter. It has its own css. Untill recently this did not affect the preview, but now the preview fails showing error message:
![image](https://user-images.githubusercontent.com/8665274/38731780-03753d6e-3f1c-11e8-992e-34948547ca94.png)

Any way to tell the preview where to find the css or bypass this issue? We would be happy if the rest of the text would preview.

**Comment by joaompinto** [comment]
Hi, thanks for reporting the problem, can you please provide a zip file with a sample .adoc and the css structure ?

Thanks

**Comment by SandMann1** [comment]
Attached is a .zip with an example. In the styles catalog you will find the coderay css. In the bin catalog you can see an example of the finished build using asciidoctor and coderay gems.

As you can see I use a setup file in the beginning. This adoc I reuse across all documents and it is always included in the beginning of my documents. As I mentioned earlyer, the main issue is that nothing previews. If you can make the syntax highlighter work in preview - great, but if the source blocks just renders genericly thats no problem. 

[adoc-previewWithCoderayProblem.zip](https://github.com/joaompinto/asciidoctor-vscode/files/1907483/adoc-previewWithCoderayProblem.zip)

**Comment by SandMann1** [comment]
Simply removing this line
`:source-highlighter: coderay`
from the setup.adoc resolves the problem for preview but breakes my butiful codeblocks in the end result.

Perhaps it is possible to just ignore this attribute before rendering?

**Comment by joaompinto** [comment]
@SandMann1, in a recent version of the extension the default asciidoc renger engine was changed from Asciidoctor (Ruby) to Asciidoctor(.JS), there are multiple source highlighters, but they only work on specific engines, you can find the list at:
https://asciidoctor.org/docs/user-manual/#enabling-source-highlighting
You have the following options:
 
1. Change setup.adoc, to use "highlightjs" instead of "coderay"
2. Change the vscode asciidoc settings to use asciidoctor (ruby):
```
    "AsciiDoc.asciidoctor_command": "asciidoctor -r asciidoctor-diagram -o-",
    "AsciiDoc.use_asciidoctor_js": false,
```

**Comment by crra** [comment]
@SandMann1  not sure if you need the diagram extension. You can remove the`-r asciidoctor-diagram`.

**Comment by SandMann1** [comment]
Thank you for excellent and quick response. - SandMan
