### ISSUE TITLE
Whitespace in document path causes "cannot read property 'document' of undefined"

### ISSUE THREAD

**Issue by pre-martin** [joaompinto/asciidoctor-vscode#73]
I am using version 0.8.0 of this plugin on Windows. The plugin is configured to use the Ruby version of asciidoctor:

    "AsciiDoc.use_asciidoctor_js": false,
    "AsciiDoc.asciidoctor_command": "D:/PS/Ruby23-x64/bin/asciidoctor.bat",

If I edit an AsciiDoc document which has a space in its path name, I get the above mentioned error. I figured out, that it looks like the plugin is not putting quotes around the path argument, which is passed to asciidoctor.bat.

When I try to open the preview for the document `D:\My Directory\file.adoc`, the plugin calls `asciidoctor.bat` with the following arguments:

    -q -o- - -B D:\My Directory

**Comment by planetrenner-martin** [comment]
Seems to happen here:

https://github.com/joaompinto/asciidoctor-vscode/blob/2c00c16e025f6a668db847216d6c981cf8975de5/src/text-parser.ts#L53

**Comment by planetrenner-martin** [comment]
I have no idea if there is a "javascript" way to do this, but the following line solves my problem:

```javascript
var asciidoctor = spawn(asciidoctor_command, ['-q', '-o-', '-', '-B', '\'' + documentPath + '\''], options );
```
