### ISSUE TITLE
Problem with scopes

### ISSUE THREAD

**Issue by sanguine8082** [joaompinto/asciidoctor-vscode#8]
It looks like there is a problem with the detection for `__git_ps1` and other underscores within back ticks.  

This is what my code snippet looks like with `__git_ps1` in it.

![image](https://cloud.githubusercontent.com/assets/8801258/22794046/5815f05e-eeb7-11e6-84d0-9871d9c18be7.png)

If I escape the underscores, the highlighting goes back to normal.

![image](https://cloud.githubusercontent.com/assets/8801258/22794082/764ec226-eeb7-11e6-85f0-542f8bc332a5.png)

However, the escaping characters are then printed, since code is rendered as-is
![image](https://cloud.githubusercontent.com/assets/8801258/22794148/b82c6784-eeb7-11e6-85f6-42888fee68d8.png)

**Comment by sanguine8082** [comment]
If anyone else is having an issue with this, enclosing the problematic syntax with `$$` seems to fix the issue.  The `$$` is a signal to the interpreter to ignore the replacement.

**Comment by joaompinto** [comment]
This would need to be fixed/changed on the asciidoctor engine side, since you have found a workaround I am closing the issue. 

Thanks for taking the time to report it and finding a solution.
