### ISSUE TITLE
Is it possible to use Asciidoctor (ruby) unstead of asciidoctor.js?

### ISSUE THREAD

**Issue by sindzicat** [joaompinto/asciidoctor-vscode#81]
Hello!

My `test.adoc`:

```
= {docname}
:nofooter:
:imagesdir: {docname}_media

image::preview.jpg[]
```

Attribute `{docname}` doesn't work in asciidoctor.js and AsciiDoc VSCode extension but works nice when I use asciidoctor (ruby version).

I tried in settings:

```
"AsciiDoc.use_asciidoctor_js": false,
"AsciiDoc.asciidoctor_command": "C:\\Ruby25-x64\\bin\\asciidoctor",
```

but this didn't help me.

Is this possible to use Asciidoctor (ruby) unstead of asciidoctor.js?

Best regards,
Andrey.

**Comment by joaompinto** [comment]
This will be fixed for Asciidoctor.js, it's a standard attibute so it should work, will be tracked on issue https://github.com/joaompinto/asciidoctor-vscode/issues/82 .

About using Ruby, yes, it should work, but not all features will be available, do you get an error on the preview window ?

Thanks

**Comment by sindzicat** [comment]
I need to export the result as HTML. Only Ruby version of Asciidoctor can do this.

**Comment by sindzicat** [comment]
Also, there are some plugins for Asciidoctor. They are on Ruby only...

**Comment by sindzicat** [comment]
> but not all features will be available

Sorry, what features will not be available?

**Comment by joaompinto** [comment]
@sindzicat I will add an option to export to HTML (using AsciidoctorJS), yes asciidoctor (Ruby) has many plugins, that's why the option to use Ruby is still supported.

Right now the following features do not work with Asciidoctor Ruby:
- Highlight in the preview window for the section being edited 
- Automatic preview scroll to the section being edited
- Export to PDF

**Comment by rohel01** [comment]
Hello,

Can you clarify if Asciidoctor (ruby) can be used for live preview ?
Currently, I think it does not work as I get different results between live preview and manual asciidoctor invocation.

For example, I want to use the pygments plugin but it does not work in live preview

My config

```
    "AsciiDoc.use_asciidoctor_js": false,
    "AsciiDoc.asciidoctor_command": "/usr/bin/asciidoctor"
```

**Comment by joaompinto** [comment]
@rohel01 Asciidoctor ruby should work (with the limitations reported above), do you get any error in the preview window ?

**Comment by rohel01** [comment]
I am no longer at work, but sometink about an undeclared Pygments constant

2018-08-01 18:42 GMT+02:00 João Pinto <notifications@github.com>:

**Comment by rohel01** [comment]
Dear @joaompinto, glad to see progress is being made on this issue.

I have checked the referenced PR, and it will help using asciidoctor-diagram.

Do you think this will also fix my issue regarding Pygments ?

**Comment by joaompinto** [comment]
@rohel01 pygments should work using the ruby version, do you still have the problem ? Do you get some error ?

**Comment by rohel01** [comment]
I am still using 0.15.0.
I can test a new release if you make one available.

**Comment by joaompinto** [comment]
There was an update a few minutes ago, you can use the extension package:

https://github.com/joaompinto/asciidoctor-vscode/releases/download/untagged-86ddf4d7b7d57c92250f/asciidoctor-vscode-0.15.1.vsix

https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by rohel01** [comment]
The link to the vsix is dead

Le lun. 20 août 2018 à 12:26, João Pinto <notifications@github.com> a
écrit :

**Comment by joaompinto** [comment]
Sorry, that correct link is:

https://github.com/joaompinto/asciidoctor-vscode/releases/download/v0.15.1/asciidoctor-vscode-0.15.1.vsix

**Comment by rohel01** [comment]
Using the vsix you supplied, I configured itto use my ruby install of
Asciidoctor. I am happy to confirm that the live preview now can:

   1. Use Pygments as a source highlighter
   2. Have PlantUML diagrams rendered via the ascidoctor-diagram extension

Thank you for your work

Le lun. 20 août 2018 à 13:00, João Pinto <notifications@github.com> a
écrit :
