### ISSUE TITLE
Option to use default stylesheet

### ISSUE THREAD

**Issue by danyill** [joaompinto/asciidoctor-vscode#98]
This extension is just getting better all the time. Thanks for your hard work on it.

For my use case I would prefer the output styling to match the default Asciidoctor stylesheet (the way this extension used to work some time ago). This is because I prefer these styles (aesthetically) and also because they will reflect the output which is produced by my build system which uses the default stylesheets.

It would be great if we could have this as an option.

**Comment by abelsromero** [comment]
I am wondering what happened to this feature.
It seems at some point it was removed, but I think it's a good addition to offer an "out of the box" preview to users.
